posix/socket: fix missing include
This adds a missing include which is included in other source files,
but not in this one. Without it, a compilation error results:
```console
external/aws-c-io/source/posix/socket.c: In function 's_update_local_endpoint':
external/aws-c-io/source/posix/socket.c:347:74: error: expected ')' before 'PRIu32'
         snprintf(tmp_endpoint.address, sizeof(tmp_endpoint.address), "%" PRIu32, s->svm_cid);
                                                                          ^~~~~~
external/aws-c-io/source/posix/socket.c:347:71: warning: spurious trailing '%' in format [-Wformat=]
         snprintf(tmp_endpoint.address, sizeof(tmp_endpoint.address), "%" PRIu32, s->svm_cid);
```